version: "3.7"
services:
  producer:
    build: producer/.
    ports:
      - '8000:8000'
    container_name: kafka-producer
    restart: always
    depends_on:
      - kafka
    environment:
      - "KAFKA_SERVER=kafka:9092"
  consumer:
    build: consumer/.
    restart: always
    depends_on:
      - kafka
    environment:
      - "KAFKA_SERVER=kafka:9092"
      - "KAFKA_TOPICS=do-work,do-work2"
      - "KAFKA_CONSUMER_GROUP=example-consumer"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
  kafka:
    build: kafka/.
    ports:
      - '2181:2181'
      - '9092:9092'
    environment:
      -  "ALLOW_ANONYMOUS_LOGIN=yes"
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
